version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: be-action-analysis
    ports:
      - '3005:3005'
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
